version: '3.8'

services:
  # Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: aigallery-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/gallery.db:/app/gallery.db
    environment:
      - DATABASE_URL=sqlite:///./gallery.db
      - SECRET_KEY=your-secret-key-change-in-production
      - ALIST_URL=http://alist:5244
      - ALIST_USERNAME=admin
      - ALIST_PASSWORD=admin123
      - ALIST_UPLOAD_PATH=/gallery
    depends_on:
      - alist
    networks:
      - aigallery

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: aigallery-frontend
    ports:
      - "4321:4321"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    networks:
      - aigallery

  # Alist (Openlist)
  alist:
    image: xhofe/alist:latest
    container_name: aigallery-alist
    restart: unless-stopped
    ports:
      - "5244:5244"
    volumes:
      - alist_data:/opt/alist/data
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
    networks:
      - aigallery

  # Nginx (Production)
  nginx:
    image: nginx:alpine
    container_name: aigallery-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - backend
      - frontend
      - alist
    networks:
      - aigallery
    profiles:
      - production

volumes:
  alist_data:

networks:
  aigallery:
    driver: bridge